route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'PromitheusBot'
            channel: '#monitoring'
            api_url: '<placeholder>'