global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'app'
    ec2_sd_configs:
      - region: eu-central-1
        access_key: <akplaceholder>
        secret_key: <skplaceholder>
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: Gulp.*
        action: keep
      - source_labels: [__meta_ec2_public_dns_name]
        target_label: instance
        replacement: '${1}:9100'



  - job_name: 'db'
    ec2_sd_configs:
      - region: eu-central-1
        access_key: <akplaceholder>
        secret_key: <skplaceholder>
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: DB.*
        action: keep
      - source_labels: [__meta_ec2_public_dns_name]
        target_label: instance
        replacement: '${1}:9100'

rule_files:
  - /etc/prometheus/*.rules

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'