---
# tasks file for grafana

- name: Install Deps.
  apt: pkg=apt-transport-https state=present

- name: Add Grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Add Grafana repo key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Install Grafana
  apt: pkg=grafana state=present update_cache=true
  notify:
    - Restart Grafana

- name: Enable Grafana
  service: name=grafana-server enabled=yes

