---
# tasks file for prometheus

- name: Install Prometheus Components
  apt: pkg={{ item }} state=present update_cache=true
  with_items:
    - prometheus
    - prometheus-pushgateway
    - prometheus-alertmanager

- name: Remove The Old node_exporter
  apt: pkg=prometheus-node-exporter state=absent update_cache=true

- name: Add Prometheus Config
  template: src=prometheus.yml dest=/etc/prometheus/prometheus.yml
  notify:
      - Restart Prometheus

- name: Add Alert Manager Config
  template: src=alertmanager.yml dest=/etc/prometheus/alertmanager.yml
  notify:
      - Restart Alert Manager
      - Restart Prometheus

- name: Add Alert Manager Rules
  copy: src=hoststats-alert.rules dest=/etc/prometheus/hoststats-alert.rules
  notify:
      - Restart Alert Manager
      - Restart Prometheus

- name: Enable Prometheus
  service: name=prometheus enabled=yes

- name: Enable Alertmanager
  service: name=prometheus-alertmanager enabled=yes

- name: Install docker-py (pip)
  pip:
    name: docker-py

- name: Adding hosts file for docker (Used for HTTP AUTH)
  lineinfile:
    path: /srv/hosts
    state: present
    line: '127.0.0.1    web'
    create: yes

- name: Add Basic HTTP Auth (Docker) 
  docker_container:
    name: nginx_http_auth
    image: beevelop/nginx-basic-auth
    state: started
    network_mode: host
    volumes:
            - /srv/hosts:/etc/hosts
    env:
      HTPASSWD: 'admin:$apr1$7BbFpIy7$hgxAEYH6W3C1YCc3BoYwM1'
      FORWARD_PORT: 9090
