---
# tasks file for prometheus

- name: Install Prometheus Components
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - prometheus
    - prometheus-pushgateway
    - prometheus-alertmanager

- name: Add Prometheus Config
  template: src=prometheus.yml dest=/etc/prometheus/prometheus.yml
  notify:
      - Restart Prometheus

- name: Add Alert Manager Config
  template: src=alertmanager.yml dest=/etc/prometheus/alertmanager.yml
  notify:
      - Restart Alert Manager
      - Restart Prometheus

- name: Add Alert Manager Rules
  template: src=hoststats-alert.rules dest=/etc/prometheus/rules/hoststats-alert.rules
  notify:
      - Restart Alert Manager
      - Restart Prometheus