---
# tasks file for prometheus

- name: Install Prometheus Components
  apt: pkg={{ item }} state=present update_cache=true
  with_items:
    - prometheus
    - prometheus-pushgateway
    - prometheus-alertmanager

- name: Remove The Old node_exporter
  apt: pkg=prometheus-node-exporter state=absent update_cache=true

- name: Add Prometheus Config
  template: src=prometheus.yml dest=/etc/prometheus/prometheus.yml
  notify:
      - Restart Prometheus

- name: Add Alert Manager Config
  template: src=alertmanager.yml dest=/etc/prometheus/alertmanager.yml
  notify:
      - Restart Alert Manager
      - Restart Prometheus

- name: Add Alert Manager Rules
  copy: src=hoststats-alert.rules dest=/etc/prometheus/hoststats-alert.rules
  notify:
      - Restart Alert Manager
      - Restart Prometheus

- name: Enable Prometheus
  service: name=prometheus enabled=yes

- name: Enable Alertmanager
  service: name=prometheus-alertmanager enabled=yes
